GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJKdXN0aW4gIiwiZW1haWwiOiJKdXN0aW5AZ21haWwuY29tIiwiaWF0IjoxNjg1Njk1OTcyLCJleHAiOjE2ODU2OTYwMDJ9.Lyaqs0OJmmBxQXRfcS5ZWLds4rY8mZC0cgHevA-_I5Q"
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Justin",
    "email": "Justin@gmail.com",
    "password": "123456",
    "confPassword": "123456" 
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Justin@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
POST http://localhost:5000/address
Content-Type: application/json

{
    "province": "West Java",
    "city": "Depok",
    "regency": "Pancoran Mas",
    "details": "blablabalbalbalabla abl bal balabl ala",
    "postal_code": 16356,
    "userId": 2
}

###
GET http://localhost:5000/address/1

###
PUT http://localhost:5000/address/2
Content-Type: application/json

{
    "province": "West Java",
    "city": "Depok",
    "regency": "Pancoran Mas",
    "details": "updated address",
    "postal_code": 16356,
    "userId": 2
}